LiveUsb1, as previous

diff --git a/LiveUsb1 b/LiveUsb1
--- a/LiveUsb1
+++ b/LiveUsb1
@@ -710,7 +710,7 @@ pause_and_check() {
 ## Note: this brace grouping (all together of for_admin, for_bash, etc.) is so that "shellcheck disable" will 
 #+  apply to the entire block
 
-rpm_count_A=$( rpm -qa | sha256sum | awk '{ print $1 }' )
+hash_of_installed_rpms_A=$( rpm -qa | sha256sum | awk '{ print $1 }' )
 rpm_nms_for_removal=( google-noto-sans-cjk-vf-fonts mint-x-icons mint-y-icons transmission )
 
 # shellcheck disable=SC2206
@@ -766,8 +766,9 @@ then
         er_x Line:"${nL}", "${removable_rpms[rr]}"
       fi
     done
-
-    command rm --one-file-system --preserve-root=all --force -- "${tmpd}/removable_rpms.array"
+     
+    [[ -f "${tmpd}/removable_rpms.array" ]] && 
+      command rm --one-file-system --preserve-root=all --force -- "${tmpd}/removable_rpms.array"
   fi
 fi
 
@@ -777,6 +778,39 @@ fi
 :;: 'Then do a blanket security upgrade'
 
   pause_and_check "$nL" # <>
+
+## Count the original number of rpms installed
+
+## Get full list of rpms to upgrade, in an array; exit on non-zero
+
+
+
+## For each "original rpm" in the original list
+
+  ## Loop A, open
+
+  ## Re-run the list, grepping for the "original rpm"
+
+  ## If the "original rpm" is NA in the new list of rpms-to-be-upgraded
+
+    ## then unset the "original rpm" index and continue with the next iteration of Loop A
+
+  ## Otherwise, if the "original rpm" still needs to be upgraded
+
+    ## then upgrade just that one "original rpm"; exit on non-zero
+
+    ## Run "needs-restarting"
+
+    ## pause-to-check
+
+    ## Restart PIDs as necessary, using multiple signals; exit on non-zero
+
+  ## Loop A, shut
+
+## Loop A, end
+
+
+
 
 sudo -- nice --adjustment=-20 -- dnf --assumeyes --quiet --security upgrade || er_x "${nL}"
 
@@ -842,9 +876,9 @@ get_pids_for_restarting
   #declare -p pr_counter # <>
   #ec=101 nn="$nL" exit # <>
 
-rpm_count_B=$( rpm -qa | sha256sum | awk '{ print $1 }' )
+hash_of_installed_rpms_B=$( rpm -qa | sha256sum | awk '{ print $1 }' )
 
-if ! [[ ${rpm_count_A} = "${rpm_count_B}" ]] || [[ "${#a_pids[@]}" -gt 0 ]]
+if ! [[ ${hash_of_installed_rpms_A} = "${hash_of_installed_rpms_B}" ]] || [[ "${#a_pids[@]}" -gt 0 ]]
 then
   while true
   do
