LiveUsb1: move section on gh from LiveUsb2 into LiveUsb1

diff --git a/LiveUsb1 b/LiveUsb1
--- a/LiveUsb1
+++ b/LiveUsb1
@@ -293,24 +293,6 @@ declare BASHRCSOURCED USER_LS_COLORS ## Note: /etc/bashrc and /etc/profile.d/col
 :;: 'Regular users with sudo, only'
 must_be_root
 
-:;: 'Minimum necessary rpms'
-for XX in git gh ShellCheck
-do
-  if ! rpm -q --quiet "$XX"
-  then
-    sudo dnf --assumeyes install "$XX"
-    if sudo dnf needs-restarting
-    then
-      er_x "${nL}" needs-restarting "$XX"
-    fi
-  fi
-done
-
-:;: 'Minimum necessary git and gh commands'
-git config --global 'user.email' '84648683+wileyhy@users.noreply.github.com'
-git config --global 'user.name' 'Wiley Young'
-git config --global 'user.signingkey' 'E287D0CF528591CE'
-
 :;: 'Certain files must have been installed from off-disk'
 files_for_use_with_github=( ~/.ssh ~/.gnupg ~/.config/gh ~/.config/procps/toprc ~/.vimrc ) 
 
@@ -383,6 +365,79 @@ time sudo -- chronyc makestep > /dev/null
 
   #ec=101 nn="$nL" exit # <>
   #set -x # <>
+
+:;: 'Minimum necessary rpms'
+for XX in git gh ShellCheck
+do
+  if ! rpm -q --quiet "$XX"
+  then
+    sudo dnf --assumeyes install "$XX"
+    if sudo dnf needs-restarting
+    then
+      er_x "${nL}" needs-restarting "$XX"
+    fi
+  fi
+done
+
+:;: 'Minimum necessary git commands'
+git config --global 'user.email' '84648683+wileyhy@users.noreply.github.com'
+git config --global 'user.name' 'Wiley Young'
+git config --global 'user.signingkey' 'E287D0CF528591CE'
+
+:;: 'gh -- github CLI'
+#gh auth status > /dev/null
+declare -A github_configs=( [editor]=vim [browser]=firefox [pager]=less [git_protocol]=ssh )
+gh_config_list_out=$( gh config list | tr '\n' ' ' )
+
+for ff in "${!github_configs[@]}"
+do 
+  if ! [[ ${gh_config_list_out} = "${ff}=${github_configs[$ff]}" ]]
+  then
+    gh config set "${ff}" "${github_configs[$ff]}"
+  fi
+done
+unset gh_config_list_out github_configs ff
+
+:;: 'gh -- Log in'
+
+:;: 'gh -- Define a login command'
+function gh_auth_login_command(){ :
+  ## Note: do not break this line with any backslashed newlines or it will fail and you'll have to refresh auth manually
+  if gh auth status 2> /dev/null 1>&2
+  then
+    gh auth logout 2> /dev/null 1>&2
+  fi
+  
+  gh auth login --git-protocol 'ssh' --hostname 'github.com' --scopes 'admin:public_key,read:gpg_key,admin:ssh_signing_key' --web || 
+    exit "${nL}"
+ 
+  : 'gh - Use GitHub CLI as a credential helper'
+  git config --global credential.helper "cache --timeout=3600"
+  gh auth setup-git
+}
+
+:;: 'gh -- Login to github'
+## Note: executing this command just once
+if ! gh auth status 2> /dev/null 1>&2 || [[ $( gh auth status |& grep --count $'\xe2\x9c\x93' ) -ne 4 ]]
+then
+  gh_auth_login_command
+fi
+
+:;: 'gh -- Get SSH & GPG keys'
+for gg in ssh-key gpg-key
+do
+  if ! gh "${gg}" list > /dev/null
+  then
+    gh_auth_login_command
+  fi
+done
+unset gg
+
+:;: 'gh -- Review auth'
+printf '\n'
+gh auth status 
+
+  #exit $nL # <>
 
 :;: 'Bash'
 ## Note: this section is for .bashrc. VTE functions are from Fedora 38, Sun 09 July 2023, altered from vte.sh
