./LiveUsb1

diff --git a/LiveUsb1 b/LiveUsb1
--- a/LiveUsb1
+++ b/LiveUsb1
@@ -852,14 +852,25 @@ fi
 ## Note, you want for these array elements to represent just one parameter or function each
 unset bashrc_strings_1 bashrc_strings_2
 
-: '  bashrc: Functions (a.k.a. "subroutines")'
-for LL in "${fcns_for_appending_into_bashrc[@]}"
+: '  bashrc: Variables'
+for LL in "${vars_for_appending_into_bashrc[@]}"
 do
   if ! [[ "$( printf -pF __vte_prompt_command )" = "not found" ]]
   then
     bashrc_strings_1+=( ["subroutine ${LL}"]="function $( declare -pf "${LL}" )" )
   fi
 done
+unset LL
+
+: '  bashrc: Functions (a.k.a. "subroutines")'
+for MM in "${fcns_for_appending_into_bashrc[@]}"
+do
+  if ! [[ "$( printf -pF __vte_prompt_command )" = "not found" ]]
+  then
+    bashrc_strings_1+=( ["subroutine ${MM}"]="function $( declare -pf "${MM}" )" )
+  fi
+done
+unset MM
 
 : '  bashrc: Variables'
 bashrc_strings_2=(                   ['define BROWSER']=$(            declare -p BROWSER ) )
