./LiveUsb1

diff --git a/LiveUsb1 b/LiveUsb1
--- a/LiveUsb1
+++ b/LiveUsb1
@@ -1304,75 +1304,74 @@ mapfile -d '' -t rpms_for_upgrade < <( dnf --assumeno upgrade 2>/dev/null | awk 
 
   echo "count, rpms_for_upgrade, ${#rpms_for_upgrade[@]}"
 
-## For each "original rpm" in the original list
-for XX in "${!all_installed_rpms[@]}"; 
-do 
-  ## Loop A, open
+## If there are any rpms that need security upgrades
+if [[ -n "${rpms_for_upgrade[*]:0:8}" ]]
+then
+  ## For each "original rpm" in the original list
+  for XX in "${!all_installed_rpms[@]}"; 
+  do 
+    ## Loop A, open
     
-  ## Re-run the list, grepping for the "original rpm"
-  for YY in "${rpms_for_upgrade[@]}" ; 
-  do 
-    regexp="^${YY}-[0-9]{,16}(\.[0-9]{,16}){,8}-.*\.fc[0-9]{2,3}\.(noarch|x86-64)"; 
+    ## Re-run the list, grepping for the "original rpm"
+    for YY in "${rpms_for_upgrade[@]}" ; 
+    do 
+      regexp="^${YY}-[0-9]{,16}(\.[0-9]{,16}){,8}-.*\.fc[0-9]{2,3}\.(noarch|x86-64)"; 
       
-    ## If the "original rpm" needs to be upgraded
-    if [[ "${all_installed_rpms[XX]}" =~ $regexp ]]; 
-    then 
-        # <>
-        echo "$XX : ${all_installed_rpms[XX]}" ; 
-        echo "${all_installed_rpms[XX]}" | grep -cEe "$regexp"
-        set -x; 
-        [[ "${all_installed_rpms[XX]}" =~ $regexp ]]; 
-        echo $?; 
-        set -; 
-    fi
+      ## If the "original rpm" needs to be upgraded
+      if [[ "${all_installed_rpms[XX]}" =~ $regexp ]]; 
+      then 
+          # <>
+          echo "$XX : ${all_installed_rpms[XX]}" ; 
+          echo "${all_installed_rpms[XX]}" | grep -cEe "$regexp"
+          set -x; 
+          [[ "${all_installed_rpms[XX]}" =~ $regexp ]]; 
+          echo $?; 
+          set -; 
+      fi
+    done
+    unset YY
+
+      pause_to_check "$nL" # <>
+
+    for ZZ in "${rpms_for_upgrade[@]}" ; 
+    do 
+      regexp="^${ZZ}-[0-9]{,16}(\.[0-9]{,16}){,8}-.*\.fc[0-9]{2,3}\.(noarch|x86-64)"; 
+
+      if [[ "${all_installed_rpms[XX]}" =~ $regexp ]]; 
+      then 
+
+        ## then upgrade just that one "original rpm"; exit on non-zero
+        sudo -- nice --adjustment=-20 -- dnf --verbose upgrade "$ZZ" || er_x "$nL" "$ZZ"
+
+        ## Run "needs-restarting"
+        readarray -t nr_pids < <(\
+          sudo -- nice --adjustment=-20 -- dnf --quiet needs-restarting 2>/dev/null | awk '{ print $1 }' )
+
+          declare -p nr_pids # <>
+          pause_to_check "$nL" # <>
+
+        ## Restart PIDs as necessary, using multiple signals; exit on non-zero
+        for WW in "${nr_pids[@]}"
+        do
+          sudo -- nice --adjustment=-20 -- "$(type -P kill)" --verbose \
+            --timeout 1000 HUP \
+            --timeout 1000 USR1 \
+            --timeout 1000 TERM \
+            --timeout 1000 KILL -- "$WW"
+        done
+        unset WW
+
+      ## If the "original rpm" is NA in the new list of rpms-to-be-upgraded
+      else
+        ## then unset the "original rpm" index and continue with the next iteration of Loop A
+        unset 'all_installed_rpms[XX]'
+      fi; 
+    done; 
+    unset ZZ
   done
-  unset YY
-
-    pause_to_check "$nL" # <>
-
-  for ZZ in "${rpms_for_upgrade[@]}" ; 
-  do 
-    regexp="^${ZZ}-[0-9]{,16}(\.[0-9]{,16}){,8}-.*\.fc[0-9]{2,3}\.(noarch|x86-64)"; 
-
-    if [[ "${all_installed_rpms[XX]}" =~ $regexp ]]; 
-    then 
-
-      ## then upgrade just that one "original rpm"; exit on non-zero
-      sudo -- nice --adjustment=-20 -- dnf --verbose upgrade "$ZZ" || er_x "$nL" "$ZZ"
-
-      ## Run "needs-restarting"
-      readarray -t nr_pids < <(\
-        sudo -- nice --adjustment=-20 -- dnf --quiet needs-restarting 2>/dev/null | awk '{ print $1 }' )
-
-        declare -p nr_pids # <>
-        pause_to_check "$nL" # <>
-
-      ## Restart PIDs as necessary, using multiple signals; exit on non-zero
-      for WW in "${nr_pids[@]}"
-      do
-        sudo -- nice --adjustment=-20 -- "$(type -P kill)" --verbose \
-          --timeout 1000 HUP \
-          --timeout 1000 USR1 \
-          --timeout 1000 TERM \
-          --timeout 1000 KILL -- "$WW"
-      done
-      unset WW
-
-    ## If the "original rpm" is NA in the new list of rpms-to-be-upgraded
-    else
-      ## then unset the "original rpm" index and continue with the next iteration of Loop A
-      unset 'all_installed_rpms[XX]'
-    fi; 
-  done; 
-  unset ZZ
-done
-unset XX
-
+  unset XX
+fi
 exit 101
-
-
-
-
 
   ## Loop A, shut
 
