./LiveUsb1

diff --git a/LiveUsb1 b/LiveUsb1
--- a/LiveUsb1
+++ b/LiveUsb1
@@ -1146,31 +1146,80 @@ fi
 ## Note, the problem with this "blanket security upgrade" is how it includes kernel and firmware. Better to
 #+  capture list of rpms in a no-op cmd, filter out impractical (for a LiveUsb) rpms, then upgrade the rest.
 
+
   #pause_to_check "$nL" # <>
 
 ## Count the original number of rpms installed
+mapfile -d '' -t all_installed_rpms < <( rpm -qa 2>/dev/null | awk '{ printf "%s\0", $1 }' )
+count="${#all_installed_rpms[@]}"
 
 ## Get full list of rpms to upgrade, in an array; exit on non-zero
+mapfile -d '' -t rpms_for_upgrade < <( dnf --assumeno upgrade 2>/dev/null | awk '$2 ~ /x86_64|noarch/ { printf "%s\0", $1 }' )
 
-## For each "original rpm" in the original list
 
-  ## Loop A, open
+  ## For each "original rpm" in the original list
+  for XX in "${!all_installed_rpms[@]}"; 
+  do 
+    ## Loop A, open
+    
+    ## Re-run the list, grepping for the "original rpm"
+    for YY in "${rpms_for_upgrade[@]}" ; 
+    do 
+      regexp="^${YY}-[0-9]{,16}(\.[0-9]{,16}){,8}-.*\.fc[0-9]{2,3}\.(noarch|x86-64)"; 
+      
+      ## If the "original rpm" needs to be upgraded
+      if [[ "${all_installed_rpms[XX]}" =~ $regexp ]]; 
+      then 
+          # <>
+          echo $XX : "${all_installed_rpms[XX]}" ; 
+          echo "${all_installed_rpms[XX]}" | grep -cEe "$regexp"
+          set -x; 
+          [[ "${all_installed_rpms[XX]}" =~ $regexp ]]; 
+          echo $?; 
+          set -; 
+      fi
+    done
 
-  ## Re-run the list, grepping for the "original rpm"
+      pause_to_check $nL # <>
 
-  ## If the "original rpm" is NA in the new list of rpms-to-be-upgraded
+    for YY in "${rpms_for_upgrade[@]}" ; 
+    do 
+      if [[ "${all_installed_rpms[XX]}" =~ $regexp ]]; 
+      then 
 
-    ## then unset the "original rpm" index and continue with the next iteration of Loop A
+        ## then upgrade just that one "original rpm"; exit on non-zero
+        sudo -- nice --adjustment=-20 -- dnf --verbose upgrade "$YY" || er_x "$nL" "$YY"
 
-  ## Otherwise, if the "original rpm" still needs to be upgraded
+        ## Run "needs-restarting"
+        readarray -t nr_pids < <(\
+          sudo -- nice --adjustment=-20 -- dnf --quiet needs-restarting 2>/dev/null | awk '{ print $1 }' )
 
-    ## then upgrade just that one "original rpm"; exit on non-zero
+          declare -p nr_pids # <>
+          pause_to_check $nL # <>
 
-    ## Run "needs-restarting"
+        ## Restart PIDs as necessary, using multiple signals; exit on non-zero
+        for WW in "${nr_pids[@]}"
+        do
+          sudo -- nice --adjustment=-20 -- "$(type -P kill)" --verbose \
+            --timeout 1000 HUP \
+            --timeout 1000 USR1 \
+            --timeout 1000 TERM \
+            --timeout 1000 KILL -- "$WW"
+        done
 
-    ## pause-to-check
+      ## If the "original rpm" is NA in the new list of rpms-to-be-upgraded
+      else
+        ## then unset the "original rpm" index and continue with the next iteration of Loop A
+        unset 'all_installed_rpms[XX]'
+      fi; 
+    done; 
+  done
 
-    ## Restart PIDs as necessary, using multiple signals; exit on non-zero
+
+
+
+
+
 
   ## Loop A, shut
 
