./LiveUsb1

diff --git a/LiveUsb1 b/LiveUsb1
--- a/LiveUsb1
+++ b/LiveUsb1
@@ -809,17 +809,10 @@ missing_vars_and_fns=()
 #+  turn must be defined prior to defining these arrays
 
 :;: 'Define lists of parameters to be appended into bashrc'
-vars_for_appending_into_bashrc=( 
-  'BROWSER'
-  'EDITOR'
-  'PROMPT_COMMAND'
-  'PS0'
-)
-fcns_for_appending_into_bashrc=( 
-  'rm' 
-  #'__vte_osc7' '__vte_prompt_command' 
-)
+vars_for_appending_into_bashrc=( 'BROWSER' 'EDITOR' 'PROMPT_COMMAND' 'PS0' )
+fcns_for_appending_into_bashrc=( 'rm' ) #'__vte_osc7' '__vte_prompt_command' 
 
+#: 'Arrays must exist'
 #[[ -z ${vars_for_appending_into_bashrc[*]} ]] && er_x "${nL}"
 #[[ -z ${fcns_for_appending_into_bashrc[*]} ]] && er_x "${nL}"
 
@@ -852,33 +845,27 @@ fi
 
 :;: 'Define bashrc_strings_*'
 ## Note, you want for these array elements to represent just one parameter or function each
-unset bashrc_strings_F bashrc_strings_V
+unset bashrc_strings_V bashrc_strings_F 
 
 : '  bashrc: Variables'
-for LL in "${vars_for_appending_into_bashrc[@]}"
+for VV in "${vars_for_appending_into_bashrc[@]}"
 do
-  if ! [[ "$( printf -p "${LL}" )" =~ "not found" ]]
+  if ! [[ "$( printf -p "${VV}" )" =~ "not found" ]]
   then
-    bashrc_strings_F+=( ["subroutine ${LL}"]="function $( declare -pf "${LL}" )" )
+    bashrc_strings_V+=( ["define variable ${VV}"]=$( declare -p "${VV}" ) )
   fi
 done
-unset LL
+unset VV
 
 : '  bashrc: Functions (a.k.a. "subroutines")'
-for MM in "${fcns_for_appending_into_bashrc[@]}"
+for FF in "${fcns_for_appending_into_bashrc[@]}"
 do
-  if ! [[ "$( printf -pF "${MM}" )" =~ "not found" ]]
+  if ! [[ "$( printf -pF "${FF}" )" =~ "not found" ]]
   then
-    bashrc_strings_F+=( ["subroutine ${MM}"]="function $( declare -pf "${MM}" )" )
+    bashrc_strings_F+=( ["define subroutine ${FF}"]="function $( declare -pf "${FF}" )" )
   fi
 done
-unset MM
-
-: '  bashrc: Variables'
-bashrc_strings_V=(                   ['define BROWSER']=$(            declare -p BROWSER ) )
-bashrc_strings_V+=(                   ['define EDITOR']=$(            declare -p EDITOR ) )
-bashrc_strings_V+=(           ['define PROMPT_COMMAND']=$(            declare -p PROMPT_COMMAND ) )
-bashrc_strings_V+=(                      ['define PS0']=$(            declare -p PS0  ) )
+unset FF
 
 :;: 'Do some backups'
 for VV in "${files_for_use_with_bash[@]}"
